---
# tasks file for s3cmd

- name: Installing {{ s3cmd_debian_pre_reqs }} on Debian based systems as pre-requisite.
  package:
    name: "{{ s3cmd_debian_pre_reqs }}"
    state: "{{ s3cmd_debian_pre_reqs_desired_state }}"
    force_apt_get: yes

- name: Installing {{ s3cmd_app_debian_package }} on Debian based systems.
  pip:
    executable: "{{ s3cmd_pip_executable }}"
    name: "{{ s3cmd_app_debian_package }}"
    state: "{{ s3cmd_desired_state }}"
